### ISSUE TITLE
progressUpdate broken for non-tiny files

### ISSUE THREAD

**Issue by Thomee** [barak/vobcopy#4]
The changes to progressUpdate to avoid division by zero now cause an integer overflow on files with a meaningful size. In an 80 column terminal, barLen is 64, so this happens when the current file size is over 32MiB. The fix is to cast the values as long when calculating numChars:
```
2256c2256
< 	  numChars = cur * barLen / tot;
---
> 	  numChars = (long)cur * (long)barLen / (long)tot;

```

**Comment by barak** [comment]
Merged in 9cfded85916d6bd567f49e3e96497dc8e0e80ee0
