### ISSUE TITLE
vobcopy.org web site hacked ?

### ISSUE THREAD

**Issue by fillods** [barak/vobcopy#8]
Hi,

http://vobcopy.org web site looks like hacked or diverted.

Here, right now it resolves to 141.0.17.175, eventually to http://www.88kacakbahis.com/superbahis.php which looks like squatting.

According to the WaybackMachine, the last known good page is in May 2018 https://web.archive.org/web/20180520195630/http://vobcopy.org:80/

http://vobcopy.org is mentioned in source code in `configure.ac` and `vobcopy.spec`
The URL is also mentioned in the About section of this GitHub repo (that is https://github.com/barak/vobcopy).

Were is the new home of vobcopy ? It looks like this GitHub repo is the best I've found so far. Thanks for the maintaining work.

**Comment by barak** [comment]
Yeah, I started maintaining the package for Debian because I used it. Not using it anymore (hey dad what's that, a coaster, or maybe part of some boardgame?) so just maintaining it out of inertia. Dunno what the story is with `vobcopy.org`. If someone were to take the last snapshot off the archive and push it into the git repo in the way that causes github to publish it, I'd be happy to merge that. Can even give write access to my repo if that makes sense, if it's the de-facto upstream.

**Comment by rathann** [comment]
It looks like vobcopy.org expired on January 30th, 2019 and was taken over by squatters on March 8th, same year. Let me also say thank you for picking up vobcopy. Also, could you make a new release with the fixes accumulated so far?

**Comment by rathann** [comment]
There's another fork at https://github.com/brandc/vobcopy-fork which seems to contain a lot of good changes. Maybe you could join forces?

**Comment by barak** [comment]
> There's another fork at https://github.com/brandc/vobcopy-fork which seems to contain a lot of good changes. Maybe you could join forces?

Sure, happy to do that, or to hand over the mantle to someone else. But that particular repo hasn't been touched in years. If someone were to fork this repo and do a proper git merge --allow-unrelated-histories or whatever with that one, I'd be happy to pull the result.

**Comment by wdlkmpx** [comment]
I see `vobcopy-fork` has way too many changes... everything

I think it would be easier to just replace *.c *.h source files with the ones from the fork and apply all the needed changes and patches again (gettext, etc)

**Comment by barak** [comment]
> I think it would be easier to just replace *.c *.h source files with the ones from the fork and apply all the needed changes and patches again (gettext, etc)

This can be done and also have it be a `git merge --allow-unrelated-histories` to permit tracking changes going forward. With the right git-fu, of course.

**Comment by barak** [comment]
> could you make a new release with the fixes accumulated so far?

Doing so now.

**Comment by wdlkmpx** [comment]
Uhmm the fork compiles with fewer warnings (-Wall) than upstream, and it looks better overall, testing with dvds will require a lot of time to see which one works better..

I had to add a Makefile to test, I wonder why Brand removed the build system.

Talking about autotools, I think the project needs a cleanup. `vobcopy.mo` is a binary file that is generated and shouldn't be in the repo. The source files are *.po files

There is no `po/vobcopy.pot` file, no `po/*.po` files (translations)... that makes the gettext stuff pointless.

**Comment by wdlkmpx** [comment]
Even though the fork does basically compile without warnings on Linux... flawlessly, it appears that to be broken for FreeBSD

```
make: Leaving directory [vamps]
make: Entering directory [vobcopy]
i686-pc-freebsd11-gcc -static -DHAVE_CONFIG_H --sysroot=........
dvd.c: In function 'get_device':
dvd.c:682:1: error: expected declaration or statement at end of input
 }
 ^
```

I think the project never compiled with MinGW (Windows) because of statfs/statvfs, the preprocessor logic is quite convoluted and perhaps some simplification is required... i.e, `statvfs` is POSIX and the `statfs` stuff can be removed

**Comment by ryandesign** [comment]
> `http://vobcopy.org` web site looks like hacked or diverted.

Nearly two years later now... Can you please remove the reference to this web site from the top right corner of this GitHub project's main page, and anywhere else it may occur (configure.ac, vobcopy.spec)?

**Comment by barak** [comment]
Make a pull request?

**Comment by fillods** [comment]
Here it comes !   https://github.com/barak/vobcopy/pull/16  🙂

Also please remove the old URL that is mentioned in the About section of this GitHub repo (that is https://github.com/barak/vobcopy) by clicking the parameter icon (top right corner). Only you @barak can do it.

Many thanks !
